name: docker

on:
  workflow_call:
    inputs:
      APP_NAME:
        required: true
        type: string
      VERSION:
        required: true
        type: string

jobs:

  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: app name and img tag
        run: |
          echo "Show app name and img tag..."
          echo "APP: ${{ inputs.APP_NAME }}"
          echo "VERSION: ${{ inputs.VERSION }}"
