name: pipeline-de-testes

on:
  push


jobs:

  vars:
    uses: ./.github/workflows/set-vars.yml

  set-variables:
    needs: vars
    runs-on: macos-latest
    steps:
      - name: set vars
        run: |
          echo "## Set Vars "
          echo ${{ needs.vars.outputs.sds }}
