name: pipeline-de-testes

on:
  push


jobs:
  #---------- job 1 ------------------------
  set-vars:
    uses: ./.github/workflows/set-vars.yml
  


      # sds: {{ steps.vars.outputs.sds }}
  #----------- job 2 ----------------------
  job-1:
    needs: set-vars
    runs-on: macos-latest

    steps:
      - name: display
        id: xpto
        run: |
          echo "## Set Vars "
          echo "${{ needs.vars.outputs.sds }}"
