name: pipeline-de-testes

on:
  push


jobs:
  vars:
    uses: ./.github/workflows/set-vars.yml


      # sds: {{ steps.vars.outputs.sds }}

  set-variables:
    needs: vars
    runs-on: macos-latest
    steps:
      - name: set vars
        id: xpto
        run: |
          echo "## Set Vars "
          echo "Saudacao: ${{ needs.vars.outputs.sds }}"
