name: pipeline-de-testes

on:
  push


jobs:
  #---------- job 1 ------------------------
  set-vars:
    uses: ./.github/workflows/set-vars.yml
  


      # sds: {{ steps.vars.outputs.sds }}
  #----------- job 2 ----------------------
  job-1:
    needs: set-vars
    runs-on: macos-latest

    steps:
      - name: display
        id: xpto
        run: |
          echo "## Set Vars "
          echo "----------------------------------"
          echo "${{ needs.set-vars.outputs.sds }}"
          echo "${{ needs.set-vars.outputs.data }}"
          echo "${{ needs.set-vars.outputs.WEB }}"

  job2:
    needs: set-vars
    runs-on: macos-latest
    outputs:
      NEW_WEB: ${{ needs.set-vars.outputs.WEB }}"
    steps:
      - name: test
        run: |
          echo "WEB: ${{ needs.set-vars.outputs.WEB }}"     

  tests:
    needs: job2
    runs-on: macos-latest
    steps:
      - name: application tests
        run: |
          echo "NEW_WEB_IS: $NEW_WEB"
        env:
          NEW_WEB: ${{ needs.job2.outputs.NEW_WEB }}

  docker:
    uses: ./.github/workflows/docker.yml
    needs: set-vars
    with:
      APP_NAME: ${{ needs.set-vars.outputs.APP_NAME }}
      IMG_TAG: ${{ needs.set-vars.outputs.IMG_TAG}}