name: set-vars

on:
  workflow_call:
    outputs:
      sds:
        value: ${{ jobs.set-vars.outputs.sds }}

jobs:
  set-vars:
    runs-on: macos-latest
    outputs:
      sds: ${{ steps.resolved.outputs.saudacao }}
      ###### 
    steps:
        ####### SET VARS ###### SEND ENV ######
      - name: set vars
        id: set-vars
        run: |
          echo "## Set Vars..."
          echo "saudacao=Olá tudo bem?" >> $GITHUB_ENV
          echo "data=29/03/2025" >> $GITHUB_ENV
        ######### {{ steps.set-vars.outputs.saudacao }}
  
      - name: set outputs
        id: resolved
        run: |
          echo "## set variables"
          echo "${{ env.saudacao }}"
          echo "${{ env.data }}"
          echo "saudacao=${{ env.saudacao }}" >> $GITHUB_OUTPUT
          echo "data=${{ env.data }}" >> $GITHUB_OUTPUT

