name: set-vars

on:
  workflow_call:
    outputs:
      sds:
        value: ${{ jobs.set-vars.outputs.sds }}
      data:
        value: ${{ jobs.set-vars.outputs.data }}
      WEB:
        value: ${{ jobs.set-vars.outputs.WEB }}
      APP_NAME:
        value: ${{ jobs.set-vars.outputs.APP_NAME }}
      VERSION:
        value: ${{ jobs.set-vars.outputs.VERSION }}
jobs:
  set-vars:
    runs-on: macos-latest
    outputs:
      sds: ${{ steps.resolved.outputs.saudacao }}
      data: ${{ steps.resolved.outputs.data }}
      WEB: ${{ steps.resolved.outputs.WEB }}
      APP_NAME: ${{ steps.resolved.outputs.APP_NAME }}
      IMG_TAG: ${{ steps.resolved.outputs.IMG_NAME }}
      ######
    steps:
        ####### SET VARS ###### SEND ENV ######
      - name: set vars
        id: set-vars
        run: |
          echo "## Set Vars..."
          echo "saudacao=Olá tudo bem?" >> $GITHUB_ENV
          echo "data=29/03/2025" >> $GITHUB_ENV
          echo "WEB=www.google.com.br" >> $GITHUB_ENV
          echo "APP_NAME=app-ios-check-run" >> $GITHUB_ENV
          echo "VERSION=1.0.0" >> $GITHUB_ENV
        ######### {{ steps.set-vars.outputs.saudacao }}
  
      - name: set outputs
        id: resolved
        run: |
          echo "## set variables"
          echo "${{ env.saudacao }}"
          echo "${{ env.data }}"
          echo "${{ env.WEB }}"
          echo "${{ env.APP_NAME }}"
          echo "${{ env.VERSION }}"
          echo "-----------------------------------------------"
          echo "saudacao=${{ env.saudacao }}" >> $GITHUB_OUTPUT
          echo "data=${{ env.data }}" >> $GITHUB_OUTPUT
          echo "WEB=${{ env.WEB }}" >> $GITHUB_OUTPUT
          echo "APP_NAME=${{ env.APP_NAME }}" >> $GITHUB_OUTPUT
          echo "VERSION=${{ env.VERSION }}" >> $GITHUB_OUTPUT