name: set-vars

on:
  workflow_call:

    outputs:
      sds:
        value: ${{ jobs.get-vars.outputs.sds }}

jobs:
  set-vars:
    runs-on: macos-latest
    outputs:
      sds: ${{ steps.get-vars.outputs.saudacao }}
      ###### 
    steps:
      - name: set vars
        id: set-vars
        run: |
          echo "## Set Vars..."
          echo "saudacao=Olá tudo bem?" >> "$GITHUB_OUTPUT"
        ######### {{ steps.set-vars.outputs.saudacao }}
  
      - name: display vars
        run: |
          echo "Saudacao: ${{ env.saudacao }}"
